### ISSUE TITLE
More TODO: graphql

### ISSUE THREAD

**Issue by iamsmkr** [Pometry/Raphtory#1664]
## graphql
- [x] `wait_for_server` needs to be internalized
- [x] `wait` to be internalised into `stop` itself in python
- [x] change graphs api to return graphqls instead of vec of graphs
- [x] add precedence to config load and impl default configs
- [x] add tests graphql python
- [x] impl and add tests for client/server apis https://github.com/Pometry/Raphtory/pull/1656#issuecomment-2192094526  
- [x] Move the log_level to the server object so all config is there 
- [x] Remove timeout from run and set a sensible default (2 mins or something)
- [x] Change GQLGraphs.names to name and make this check the names of all graphs within its working_dir
    - [x] ensure any questions to GQLGraphs brings in all graphs fromthe working_dir
    - [x] For the second remove any other functions on GQLGraphs as I think they could be a little dangerous
- [x] for the RaphtoryServer.run_with_auth set it to return a result and replace all of the expects with Err
- [x] Remove Graphs hashmap/paths from the RaphtoryServer so all uploads are done via the client
- [x] Sort the different ways you have give graphs to the server, these should be:
    - [x] provide a hashmap where the keys are the filenames - these should all be set via the multipart upload as the binary string seems very slow
    - [x] provide a collection of graph files (parsed via glob (https://docs.rs/glob/latest/glob/)) for a path ON the server.
    - [x] Provide a collection of graph files on the local machine which can be uploaded via multipart upload
    - [x] All of the above functions should take a namespace argument which is the path that the graphs should be saved in within the working_dir
    - [x] All of the above should have the `overwrite` argument set to false by default where we first check if all of the names are available within the namespace and if not an error is returned
    - [x] Fix save graph and split into create_graph and update_graph apis
    - [x] improve test coverage including both storage and non-storage paths 
    - [x] Remove data invalidation where unnecessary
    - [x] Rid name as property and utilize the file name itself
    - [x] Rename rename_graph to move_graph and introduce copy_graph func

**Comment by miratepuffin** [comment]
- We dont seem to make use of `upload_graph` from the client - which should be a good bit faster than send_graph
- The load_graphs_from_path from the server and client seems to crash:
![image](https://github.com/Pometry/Raphtory/assets/6665739/fd87b084-12c0-4f3e-8623-c78de55a6864)

**Comment by miratepuffin** [comment]
```
server = RaphtoryServer(working_dir="/tmp/graphs/",port=1736)
server.start()
c = server.get_client()
c.send_graph(g,graph_name="blah",namespace="ben/tests/",overwrite=False)
c.upload_graph("/user/ben/Documents/g",graph_name="blah2",,namespace="ben/tests/",overwrite=False)
c.load_graph("/usr/ubuntu/g",graph_name="blah3",,namespace="ben/tests/",overwrite=False)
```

From discussions on simplifying the upload of graphs
